USE master 
GO

ALTER DATABASE PHONGKHAM_DB2 SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

-- 1/ Tạo DB
IF DB_ID('PHONGKHAM_DB2') IS NOT NULL
	DROP DATABASE  PHONGKHAM_DB2
GO

CREATE DATABASE PHONGKHAM_DB2
GO
USE PHONGKHAM_DB2
GO
	
-- 2/ Tạo các table + Khoá chính
-- Bảng Nhân Viên
CREATE TABLE NHANVIEN
(
	ID CHAR(8) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	NGAYSINH DATE,
	DIACHI NVARCHAR(200),
	SDT CHAR(10),
	GIOITINH VARCHAR(6) CHECK (GIOITINH IN ('Male', 'Female')),
	MATKHAU CHAR(8)
)
GO
-- Bảng Nha Sĩ	
CREATE TABLE NHASI
(
	ID char(8) PRIMARY KEY,
	HOTEN nvarchar(50),
	NGAYSINH date,
	DIACHI nvarchar(200),
	SDT char(10),
	GIOITINH VARCHAR(6) CHECK (GIOITINH IN ('Male', 'Female')),
	MATKHAU char(8)
)
GO

CREATE TABLE LICHLAMVIEC
(
	NHASI char(8),
	NGAY date,
	THOIGIAN TIME,
	TRANGTHAI binary,
	PRIMARY KEY (NHASI,NGAY,THOIGIAN),
	FOREIGN KEY (NHASI) REFERENCES NHASI(ID)
)
GO

-- Bảng QTV
CREATE TABLE QTV
(
	ID char(8) PRIMARY KEY,
	HOTEN nvarchar(50),
	NGAYSINH date,
	DIACHI nvarchar(200),
	SDT char(10),
	GIOITINH VARCHAR(6) CHECK (GIOITINH IN ('Male', 'Female')),
	MATKHAU char(8)
)
GO

CREATE TABLE BENHAN
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	HOTEN nvarchar(50),
	NGAYSINH date,
	DIACHI nvarchar(200),
	SDT char(10),
	GIOITINH VARCHAR(6) CHECK (GIOITINH IN ('Male', 'Female')),
	THONGTINTONGQUAN nvarchar(200),
	TINHTRANGDIUNG nvarchar(200),
)
GO

CREATE TABLE THUOCCHONGCHIDINH
(
	BENHNHAN INT,
	IDTHUOC INT,
	PRIMARY KEY(BENHNHAN,IDTHUOC),
)
GO

CREATE TABLE KHDIEUTRI
(
	ID INT IDENTITY(1,1),
	BENHNHAN INT,
	TRANGTHAI INT,
	PRIMARY KEY(BENHNHAN,ID),
	FOREIGN KEY (BENHNHAN) REFERENCES BENHAN(ID)
)
GO

CREATE TABLE DIEUTRI
(
	MADIEUTRI INT IDENTITY(1,1),
	BENHNHAN INT,
	KEHOACH INT,
	NHASI char(8),
	NGAY DATE,
	PRIMARY KEY(BENHNHAN,KEHOACH,MADIEUTRI),
	MOTA NVARCHAR(255),
	GIA INT,
	TRANGTHAI int,
	FOREIGN KEY (NHASI) REFERENCES NHASI(ID),
	FOREIGN KEY (BENHNHAN,KEHOACH) REFERENCES KHDIEUTRI(BENHNHAN,ID)
)
GO

CREATE TABLE RANG(
	MARANG INT IDENTITY(1,1), 
	TENRANG NVARCHAR(30)

	PRIMARY KEY(MARANG)
)
GO

CREATE TABLE MATRANG(
	MAMATRANG CHAR(1), 
	TENMATRANG NVARCHAR(40)

	PRIMARY KEY (MAMATRANG)
)
GO

CREATE TABLE CHONRANG(
	BENHNHAN INT,
	MARANG INT, 
	MAMATRANG CHAR(1), 

	PRIMARY KEY(BENHNHAN, MARANG, MAMATRANG),
	FOREIGN KEY (BENHNHAN) REFERENCES BENHAN(ID), 
	FOREIGN KEY (MARANG) REFERENCES RANG(MARANG), 
	FOREIGN KEY (MAMATRANG) REFERENCES MATRANG(MAMATRANG), 
)
GO

CREATE TABLE THANHTOAN
(
	MADIEUTRI INT IDENTITY(1,1),
	BENHNHAN INT,
	KEHOACH INT,
	PRIMARY KEY(BENHNHAN,KEHOACH,MADIEUTRI),
	LATIENMAT BINARY,
	TIENNHAN INT,
	TIENTHOI INT,
	NGAYTT DATE,
	FOREIGN KEY (BENHNHAN,KEHOACH,MADIEUTRI) REFERENCES DIEUTRI(BENHNHAN,KEHOACH,MADIEUTRI) ,
)
GO

CREATE TABLE CUOCHEN
(
	ID INT IDENTITY(1,1),
	BENHNHAN INT,
	NHASI CHAR(8),
	PRIMARY KEY(ID, BENHNHAN),
	NGAYHEN DATE,
	GIOHEN TIME,
	GHICHU NVARCHAR(200),
	TRANGTHAI BINARY,
	LATAIKHAM BINARY,
	FOREIGN KEY (BENHNHAN) REFERENCES BENHAN(ID),
	FOREIGN KEY (NHASI) REFERENCES NHASI(ID)
)
GO

-----------------
CREATE TABLE THUOC (
    ID_THUOC INT IDENTITY(1,1) PRIMARY KEY,
    TENTHUOC NVARCHAR(60),
    DONGIA INT,
    DONVI NVARCHAR(30),
	SOLUONG INT,
	HANSUDUNG DATE,
	GHICHU NVARCHAR(255)
)
GO

CREATE TABLE DONTHUOC (
	ID_DON INT IDENTITY(1,1),
	ID_BENHAN INT,
	NGAYLAPDON DATE,

	PRIMARY KEY (ID_DON, ID_BENHAN),
	FOREIGN KEY (ID_BENHAN) REFERENCES dbo.BENHAN(ID),
)
GO

CREATE TABLE CHITIETDON (
	ID_DON INT,
	ID_BENHAN INT,
	ID_THUOC INT,
	SOLUONG INT,
	GHICHU NVARCHAR(30)

	PRIMARY KEY (ID_DON, ID_BENHAN, ID_THUOC),
	FOREIGN KEY (ID_DON, ID_BENHAN) REFERENCES dbo.DONTHUOC(ID_DON, ID_BENHAN),
	FOREIGN KEY (ID_THUOC) REFERENCES dbo.THUOC(ID_THUOC)
)
GO

----------------------------------------------------------------------------------------------------------------
-- 3/ Thêm Data

-- Chèn dữ liệu cho bảng NHASI
INSERT INTO NHASI (ID, HOTEN, NGAYSINH, DIACHI, SDT, GIOITINH, MATKHAU)
VALUES
    ('NS000001', N'Nha Si 1', '1990-01-01', N'123 Đường ABC, Quận XYZ', '1234567890', 'Male', 'pass1234'),
    ('NS000002', N'Nha Si 2', '1985-05-05', N'456 Đường XYZ, Quận ABC', '0987654321', 'Female', 'pass4567');
GO

-- Chèn dữ liệu cho bảng NHÂN VIÊN
INSERT INTO dbo.NHANVIEN
(
    ID,
    HOTEN,
    NGAYSINH,
    DIACHI,
    SDT,
    GIOITINH,
    MATKHAU
)
VALUES
    ('NV000001', N'Nhân viên 1', '1990-01-01', N'123 Đường ABC, Quận XYZ', '1234567890', 'Male', 'pass1234'),
    ('NV000002', N'Nhân viên 2', '1985-05-05', N'456 Đường XYZ, Quận ABC', '0987654321', 'Female', 'pass4567');
GO

-- Chèn dữ liệu cho bảng QTV
INSERT INTO QTV (ID, HOTEN, NGAYSINH, DIACHI, SDT, GIOITINH, MATKHAU)
VALUES
    ('QTV00001', N'Quan Tri Vien 1', '1988-07-20', N'789 Đường XYZ, Quận ABC', '0123456789', 'Male', 'qtvpass');
GO

-- Chèn dữ liệu cho bảng LICHLAMVIEC
INSERT INTO dbo.LICHLAMVIEC
(
    NHASI,
    NGAY,
    THOIGIAN,
    TRANGTHAI
)
VALUES
	('NS000001', '2023-01-15', '08:00:00', 1 ),
	('NS000002', '2023-01-15', '09:00:00', 0),
	('NS000001', '2023-01-15', '09:00:00', 1);
GO

-- Chèn dữ liệu cho bảng BENHAN
INSERT INTO BENHAN (HOTEN, NGAYSINH, DIACHI, SDT, GIOITINH,  THONGTINTONGQUAN)
VALUES
    (N'Nguyen Van A', '1992-03-10', N'321 Đường XYZ, Quận ABC', '1112223333', 'Male','Tong quan benh ly 1'),
    (N'Tran Thi B', '1980-12-05', N'555 Đường ABC, Quận XYZ', '4445556666', 'Female', 'Tong quan benh ly 2');
GO

--Chèn dữ liệu cho bảng THUOC
INSERT INTO THUOC (TENTHUOC, DONGIA, DONVI, SOLUONG, HANSUDUNG, GHICHU)
VALUES 
('Paracetamol', 5000, N'Viên', 100, '2024-12-31', N'Thuốc hạ sốt'),
('Amoxicillin', 8000, N'Viên', 50, '2025-06-30', N'Kháng sinh'),
('Ibuprofen', 7000, N'Viên', 80, '2024-09-30', N'Thuốc giảm đau'),
('Aspirin', 6000, N'Viên', 120, '2024-11-30', N'Thuốc chống viêm'),
('Cetirizine', 9000, N'Viên', 30, '2025-04-30', N'Thuốc chống dị ứng');
GO

-- Inserting data into DONTHUOC table
INSERT INTO DONTHUOC (ID_BENHAN, NGAYLAPDON)
VALUES 
(1, '2023-08-15'),
(1, '2023-09-20'),
(1, '2023-10-05'),
(1, '2023-11-12'),
(2, '2023-12-03');

-- Inserting data into CHITIETDON table
INSERT INTO CHITIETDON (ID_DON, ID_BENHAN, ID_THUOC, SOLUONG, GHICHU)
VALUES 
(1, 1, 3, 20, N'2 viên/buổi/ngày')
GO







