USE PHONGKHAM_DB2
GO

--Tạo role
EXEC SP_ADDROLE 'R_QTV'
EXEC SP_ADDROLE 'R_NHASI'
EXEC SP_ADDROLE 'R_NHANVIEN'
GO


-- Tạo QTV
DECLARE @ID CHAR(8)
DECLARE @MATKHAU CHAR(8)
DECLARE @DB_NAME NVARCHAR(100)
SET @DB_NAME = 'PHONGKHAM_DB2'

DECLARE cur CURSOR FOR
SELECT ID, MATKHAU
FROM dbo.QTV
[NS000002]
OPEN cur
FETCH NEXT FROM cur INTO @ID, @MATKHAU

WHILE @@FETCH_STATUS = 0
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.sql_logins WHERE name = @ID)
    BEGIN
        EXEC SP_ADDLOGIN @ID, @MATKHAU, @DB_NAME

		EXEC SP_ADDUSER @ID, @ID, 'R_QTV'
    END

    FETCH NEXT FROM cur INTO @ID, @MATKHAU
END
CLOSE cur
DEALLOCATE cur
GO


-- Tạo Nha sĩ
DECLARE @ID CHAR(8)
DECLARE @MATKHAU CHAR(8)
DECLARE @DB_NAME NVARCHAR(100)
SET @DB_NAME = 'PHONGKHAM_DB2'

DECLARE cur CURSOR FOR
SELECT ID, MATKHAU
FROM dbo.NHASI

OPEN cur
FETCH NEXT FROM cur INTO @ID, @MATKHAU

WHILE @@FETCH_STATUS = 0
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.sql_logins WHERE name = @ID)
    BEGIN
        EXEC SP_ADDLOGIN @ID, @MATKHAU, @DB_NAME

		EXEC SP_ADDUSER @ID, @ID, 'R_NHASI'
    END

    FETCH NEXT FROM cur INTO @ID, @MATKHAU
END
CLOSE cur
DEALLOCATE cur
GO

-- Tạo Nhân viên
DECLARE @ID CHAR(8)
DECLARE @MATKHAU CHAR(8)
DECLARE @DB_NAME NVARCHAR(100)
SET @DB_NAME = 'PHONGKHAM_DB2'

DECLARE cur CURSOR FOR
SELECT ID, MATKHAU
FROM dbo.NHANVIEN

OPEN cur
FETCH NEXT FROM cur INTO @ID, @MATKHAU

WHILE @@FETCH_STATUS = 0
BEGIN
    IF NOT EXISTS (SELECT 1 FROM sys.sql_logins WHERE name = @ID)
    BEGIN
        EXEC SP_ADDLOGIN @ID, @MATKHAU, @DB_NAME

		EXEC SP_ADDUSER @ID, @ID, 'R_NHANVIEN'
    END

    FETCH NEXT FROM cur INTO @ID, @MATKHAU
END
CLOSE cur
DEALLOCATE cur
GO

-- TẠO USER


SELECT *
FROM master.sys.sql_logins;

SELECT * FROM SYS.database_principals

