
USE PHONGKHAM_DB2
GO




CREATE OR ALTER PROCEDURE SP_XEMDANHSACHCUOCHEN
AS
BEGIN
	SELECT CH.NGAYHEN, CH.GIOHEN, BA.HOTEN, NS.HOTEN, CH.NHASI AS TROKHAM, CH.PHONG, CH.TRANGTHAI
	FROM CUOCHEN CH JOIN BENHAN BA ON BA.ID = CH.BENHNHAN JOIN NHASI NS ON NS.ID = CH.NHASI
END
GO


CREATE OR ALTER PROCEDURE SP_THEMCUOCHEN
	@NGAYHEN DATE, 
	@GIOHEN TIME, 
	@NHASI CHAR(8), 
	@BENHNHAN CHAR(8), 
	@GHICHU NVARCHAR(200),
	@TRANGTHAI INT, 
	@PHONG INT
AS
BEGIN 
	IF EXISTS(SELECT 1 FROM CUOCHEN WHERE NGAYHEN = @NGAYHEN AND GIOHEN = @GIOHEN AND NHASI = @NHASI ) 
		BEGIN 
			RAISERROR (N'ĐẶT HẸN TRÙNG LỊCH VỚI 1 NHA SĨ KHÁC', 16, 1); 
			RETURN;
		END
	ELSE
	BEGIN
		INSERT INTO dbo.CUOCHEN(BENHNHAN, NHASI, NGAYHEN, GIOHEN, GHICHU, TRANGTHAI, PHONG)
		VALUES(@BENHNHAN, @NHASI, @NGAYHEN, @GIOHEN, @GHICHU, @TRANGTHAI, @PHONG)
	END

END 
GO

CREATE OR ALTER PROCEDURE SP_CAPNHATCUOCHEN
	@ID INT,
	@NGAYHEN DATE, 
	@GIOHEN TIME, 
	@NHASI CHAR(8), 
	@PHONG INT
AS
BEGIN 
	IF EXISTS(SELECT 1 FROM CUOCHEN WHERE ID = @ID ) 
		BEGIN 
			IF EXISTS(SELECT 1 FROM CUOCHEN WHERE NGAYHEN = @NGAYHEN AND GIOHEN = @GIOHEN AND NHASI = @NHASI ) 
				BEGIN 
					RAISERROR (N'ĐẶT HẸN TRÙNG LỊCH VỚI 1 NHA SĨ KHÁC', 16, 1); 
					RETURN;
				END
			ELSE
				BEGIN
					UPDATE dbo.CUOCHEN
					SET NGAYHEN = @NGAYHEN, 
						GIOHEN = @GIOHEN, 
						NHASI = @NHASI, 
						PHONG = @PHONG
					WHERE ID = @ID
				END
		END
	ELSE
		RAISERROR (N'KHÔNG TÌM THẤY CUỘC HẸN CẦN CẬP NHẬT', 16, 1); 
END 
GO

CREATE OR ALTER PROCEDURE SP_XOACUOCHEN
	@ID INT
AS
BEGIN
	IF EXISTS(SELECT 1 FROM CUOCHEN WHERE ID = @ID ) 
		DELETE FROM dbo.CUOCHEN WHERE ID = @ID
	ELSE
		RAISERROR (N'KHÔNG TÌM THẤY CUỘC HẸN CẦN XÓA', 16, 1); 
END 
GO

CREATE OR ALTER PROCEDURE SP_LOCUOCHENTHEOBENHNHAN
	@TENBENHNHAN NVARCHAR(40),
	@NGAYHEN DATE
AS
BEGIN 
	SELECT CH.NGAYHEN, CH.GIOHEN, BA.HOTEN, NS.HOTEN, CH.NHASI AS TROKHAM, CH.PHONG, CH.TRANGTHAI
	FROM CUOCHEN CH JOIN BENHAN BA ON BA.ID = CH.BENHNHAN JOIN NHASI NS ON NS.ID = CH.NHASI
	WHERE BA.HOTEN = @TENBENHNHAN AND CH.NGAYHEN = @NGAYHEN
END 
GO

CREATE OR ALTER PROCEDURE SP_LOCUOCHENTHEOPHONGKHAM
	@PHONG INT, 
	@NGAYHEN DATE
AS
BEGIN 
	SELECT CH.NGAYHEN, CH.GIOHEN, BA.HOTEN, NS.HOTEN, CH.NHASI AS TROKHAM, CH.PHONG, CH.TRANGTHAI
	FROM CUOCHEN CH JOIN BENHAN BA ON BA.ID = CH.BENHNHAN JOIN NHASI NS ON NS.ID = CH.NHASI
	WHERE CH.PHONG = @PHONG AND NGAYHEN = @NGAYHEN
END 
GO

CREATE OR ALTER PROCEDURE SP_LOCCUOCHENTHEONHASI
	@ID CHAR(8), 
	@NGAYHEN DATE
AS
BEGIN 
	SELECT CH.NGAYHEN, CH.GIOHEN, BA.HOTEN, NS.HOTEN, CH.NHASI AS TROKHAM, CH.PHONG, CH.TRANGTHAI
	FROM CUOCHEN CH JOIN BENHAN BA ON BA.ID = CH.BENHNHAN JOIN NHASI NS ON NS.ID = CH.NHASI
	WHERE CH.NHASI = @ID AND NGAYHEN = @NGAYHEN
END 
GO
/*SELECT * FROM CUOCHEN
SELECT * FROM NHASI
EXEC dbo.SP_XEMDANHSACHCUOCHEN
EXEC dbo.SP_THEMCUOCHEN '2023-12-29', '09:30:00', 'NS000002', 'BN000002', N'CÓ TIỀN SỬ NGHIỆN MA TÚY', 1, 3
EXEC DBO.SP_CAPNHATCUOCHEN 6, '2023-12-29', '16:30:00', 'NS000001', 4
EXEC dbo.SP_XOACUOCHEN 6
*/

--EXEC dbo.SP_LOCUOCHENTHEOBENHNHAN 'Nguyen van A'
--EXEC dbo.SP_LOCUOCHENTHEOPHONGKHAM 3


